import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Importation des polices locales
const FiraCodeRegular = localFont({
  src: "./fonts/FiraCode-Regular.ttf",
  variable: "--font-FiraCode-Regular",
  weight: "400",
});

const FiraCodeBold = localFont({
  src: "./fonts/FiraCode-Bold.ttf",
  variable: "--font-FiraCode-Bold",
  weight: "700",
});

const FiraCodeLight = localFont({
  src: "./fonts/FiraCode-Light.ttf",
  variable: "--font-FiraCode-Light",
  weight: "300",
});

const FiraCodeMedium = localFont({
  src: "./fonts/FiraCode-Medium.ttf",
  variable: "--font-FiraCode-Medium",
  weight: "500",
});

const FiraCodeSemiBold = localFont({
  src: "./fonts/FiraCode-SemiBold.ttf",
  variable: "--font-FiraCode-SemiBold",
  weight: "600",
});

// Importation des polices Google
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Métadonnées pour Next.js
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout racine
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FiraCodeRegular.variable} ${FiraCodeBold.variable} ${FiraCodeLight.variable} ${FiraCodeMedium.variable} ${FiraCodeSemiBold.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
