import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import { PageTransition } from "./ui/Transition_Page";
import CursorFollower from "./ui/CursorFollower";

// Polices locales
const FiraCodeRegular = localFont({
  src: "./fonts/FiraCode-Regular.ttf",
  variable: "--font-FiraCode-Regular",
  weight: "400",
});

const FiraCodeBold = localFont({
  src: "./fonts/FiraCode-Bold.ttf",
  variable: "--font-FiraCode-Bold",
  weight: "700",
});

const FleurDeLeah = localFont({
  src: "./fonts/FleurDeLeah-Regular.ttf",
  variable: "--font-FleurDeLeah",
  weight: "400",
});

// Métadonnées
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${FleurDeLeah.variable} ${FiraCodeRegular.variable} ${FiraCodeBold.variable} antialiased`}
      >
        <CursorFollower />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
