import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


// Importation des polices locales
const FiraCodeRegular = localFont({
  src: "./fonts/FiraCode-Regular.ttf",
  variable: "--font-FiraCode-Regular",
  weight: "400",
});

const FiraCodeBold = localFont({
  src: "./fonts/FiraCode-Bold.ttf",
  variable: "--font-FiraCode-Bold",
  weight: "700",
});

const FleurDeLeah = localFont({
  src: "./fonts/FleurDeLeah-Regular.ttf",
  variable: "--font-FleurDeLeah",
  weight: "400",
});

// Métadonnées pour Next.js
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> {/* Ajout de <html> avec une langue par défaut */}
      <body
        className={`${FleurDeLeah.variable} ${FiraCodeRegular.variable} ${FiraCodeBold.variable} antialiased`}
      >
       {children}
      </body> {/* Ajout de </body> */}
    </html>
  );
}
